const fs = require('fs');
let content = fs.readFileSync('src/components/MediaForensicsTab.tsx', 'utf-8');

const replacement = `
                    {/* Generated images or video */}
                    {result.image ? (
                      <div className="rounded-xl overflow-hidden border border-slate-800 relative">
                        <img src={\`data:image/jpeg;base64,\${result.image}\`} alt="Generated" className="w-full h-auto" />
                        <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-slate-900 to-transparent p-4 flex items-end">
                          <span className="text-xs text-white font-mono bg-black/50 px-2 py-1 rounded">Generated by Imagen 3 Pro</span>
                        </div>
                      </div>
                    ) : result.type === 'video' ? (
                      <div className="aspect-video bg-black border border-slate-800 rounded-xl flex items-center justify-center overflow-hidden relative group">
                         <div className="absolute inset-0 bg-gradient-to-t from-slate-900 to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex items-end p-4">
                           <span className="text-xs text-white font-mono bg-black/50 px-2 py-1 rounded">Generated by Veo 3.1</span>
                         </div>
                         <Video className="w-12 h-12 text-slate-700" />
                      </div>
                    ) : null}
`;

content = content.replace(
  /\{\/\* Placeholder for generated images or video \*\/\}[\s\S]*?\}\)/,
  replacement
);

fs.writeFileSync('src/components/MediaForensicsTab.tsx', content);
